import 'package:shop_app/models/category_model.dart';

import '../models/product.dart';

final List<Category> listCategory = [
  const Category(name: 'Popular', image: 'assets/images/cate1.png'),
  const Category(name: 'Men', image: 'assets/images/cate2.png'),
  const Category(name: 'Women', image: 'assets/images/cate3.png'),
  const Category(name: 'Kids', image: 'assets/images/cate4.png'),
];

final List<Product> listProduct = [
  Product(
    id: 1,
    name: 'Cotton shirt Regular Fit',
    quanityReview: '85',
    star: '4.9',
    price: 100,
    thumb: 'assets/images/product1.png',
    images: [
      'assets/images/product1.png',
      'assets/images/product2.png',
      'assets/images/product3.png',
      'assets/images/product4.png',
    ],
    isFavorit: false,
    quanity: 1,
    size: 0,
  ),
  Product(
    id: 2,
    name: 'Cotton shirt Regular Fit',
    quanityReview: '85',
    star: '4.9',
    price: 100,
    thumb: 'assets/images/prod1.jpeg',
    images: [
      'assets/images/prod1.jpeg',
      'assets/images/prod2.jpeg',
      'assets/images/prod3.jpeg',
      'assets/images/prod4.jpeg',
      'assets/images/prod5.jpeg',
    ],
    isFavorit: false,
    quanity: 1,
    size: 0,
  ),
  Product(
    id: 3,
    name: 'Cotton shirt Regular Fit',
    quanityReview: '85',
    star: '4.9',
    price: 100,
    thumb: 'assets/images/product1.png',
    images: [
      'assets/images/pro1.jpeg',
      'assets/images/pro2.jpeg',
      'assets/images/pro3.jpeg',
      'assets/images/pro4.jpeg',
      'assets/images/pro5.jpeg'
    ],
    isFavorit: false,
    quanity: 1,
    size: 0,
  ),
  Product(
    id: 4,
    name: 'Cotton shirt Regular Fit',
    quanityReview: '85',
    star: '4.9',
    price: 100,
    thumb: 'assets/images/pro5.jpeg',
    images: [
      'assets/images/prod1.jpeg',
      'assets/images/prod2.jpeg',
      'assets/images/prod3.jpeg',
      'assets/images/prod4.jpeg',
      'assets/images/prod5.jpeg',
    ],
    isFavorit: false,
    quanity: 1,
    size: 0,
  ),
  Product(
    id: 5,
    name: 'Cotton shirt Regular Fit',
    quanityReview: '85',
    star: '4.9',
    price: 100,
    thumb: 'assets/images/pro3.jpeg',
    images: [
      'assets/images/pro1.jpeg',
      'assets/images/pro2.jpeg',
      'assets/images/pro3.jpeg',
      'assets/images/pro4.jpeg',
      'assets/images/pro5.jpeg'
    ],
    quanity: 1,
    isFavorit: false,
    size: 0,
  ),
  Product(
    id: 6,
    name: 'Cotton shirt Regular Fit',
    quanityReview: '85',
    star: '4.9',
    price: 100,
    thumb: 'assets/images/product1.png',
    images: [
      'assets/images/product1.png',
      'assets/images/product2.png',
      'assets/images/product3.png',
      'assets/images/product4.png',
    ],
    isFavorit: false,
    quanity: 1,
    size: 0,
  ),
  Product(
    id: 7,
    name: 'Cotton shirt Regular Fit',
    quanityReview: '85',
    star: '4.9',
    price: 100,
    thumb: 'assets/images/pro1.jpeg',
    images: [
      'assets/images/pro1.jpeg',
      'assets/images/pro2.jpeg',
      'assets/images/pro3.jpeg',
      'assets/images/pro4.jpeg',
      'assets/images/pro5.jpeg'
    ],
    isFavorit: false,
    quanity: 1,
    size: 0,
  ),
  Product(
    id: 8,
    name: 'Cotton shirt Regular Fit',
    quanityReview: '85',
    star: '4.9',
    price: 100,
    thumb: 'assets/images/product1.png',
    images: [
      'assets/images/product1.png',
      'assets/images/product2.png',
      'assets/images/product3.png',
      'assets/images/product4.png',
    ],
    isFavorit: false,
    quanity: 1,
    size: 0,
  ),
];
